///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: assets/song2.aks
/// Generation time: mar 02 nov 2021 18:09:45 CET
///

/// Song 'song' metadata macros
#define song_address  0x0040
#define song_size     381
#define song_end      0x1bc

/// Song 'song' array declaration
extern void song[song_size];
